### ISSUE TITLE
How to use the template

### ISSUE THREAD

**Issue by ishu3101** [thoughtbot/templates#12]
How do you use the templates provided in this repo? What is the `$VISUAL` command? How does the template replace the placeholders like `$(PROJECT_NAME)` with their value when you create the README.md from the template?

**Comment by tute** [comment]
Hi! There is no script to install these templates into projects. They serve more as guidelines, that we copy on new projects and edit ourselves.

**Comment by tute** [comment]
`$VISUAL` is a pointer to your editor, see https://unix.stackexchange.com/questions/4859/visual-vs-editor-whats-the-difference. In my case the env. variable is `vim`.

**Comment by ishu3101** [comment]
So it means that if you change the template then you have to make the changes in the projects that you have used the template as well.

**Comment by tute** [comment]
That's right.

**Comment by ishu3101** [comment]
That just means there is more work you have to do.

**Comment by tute** [comment]
How many projects' template files do you need maintained by scripts? And how exactly would those scripts automate the work you see?
